---
title: "CCAMLR Working Group Document"
author: "Paul Burch"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  word_document:
    reference_docx: ccamlrStyle.docx
    fig_width: 5
    fig_height: 5
    fig_caption: true
csl: ccamlr-science.csl
bibliography: refs.bib
---

# Abstract

@Candy2012aem

## Structure

**write this last**

* Grabbing statement in first sentence - expand on the tile and grab the readers attention

* Give a complete and convise summary

* List messages in order of importance

* Include reason/importance, findings, implications, take home messsage


# Introduction

## Structure

* Grabbing statement - content should be captured in the first sentence and explained in the first para

* State of play - previous work, current work, gaps, incorrect or inadequate interpretations or conclusions

* Scope - geographic, taxanomic, disciplinary, methodology, empirical, modelling

* Contribution of this paper - "This study proposes a new relationship ..." Can include the Aims / Hypothesis

* No surprise endings (in conclusions) - state the take home message here (and also in the abstract and conclusions)


# Methods

** write this as analyses are undertaken**


# Results

## Structure

* Only include results relevant to the aims/hypothesis, order chronologically or by importance

* Keep the narrative flow. The topic of a paragraph should be the results of an experiment, not the figure or table in which they are presented

# Discussion

## Structure

* This study demonstrated that ... (describes the most important findings)

* Additionally ... (other findings that aren't as important)
    
* It suggests that ... (compare and contrast our finding with other studies can go into detail here)
    
* However, the limitations of this study ... ()
    
* In conclusion ... (final paragraph of the conclusions from the study)


# Acknowledgements

We would like to acknowledge ...

This study was funded through the Fisheries Research and Development Corporation
(Project 2013/013) with contributions from Austral Fisheries P/L and Australian Longline P/L.


# Appendix 1

This document was created using rmarkdown and knitr to combined R code and MS Word documentation. The following versions R and associated packages were used in its creation.


```{r}
sessionInfo()
```


# References